adminapp/urls.py
from django.urls import path
from .views import (
    AdminLogin,
    DashBoard,
    CategoryView,
    CourseView,
    AddCourse,
    AddModules,
    AddSection,
    SectionView,
    EditCourse,
    CourseMakeInactive,
    SectionDetailView,
    Category,
    ModuleDetail,
    DeleteModule,
    AddModules2,
    EditSectionView,CategoryDetailView,OrderListView, VideoListView,VideoCreateView, VideoDetailView
)

from .payments import CreateClientPayment
from .viewstest import AddSectionView, SectionDetailView



app_name = "adminapp"


urlpatterns = [
    path("login/", AdminLogin.as_view(), name="login"),
    path("", DashBoard.as_view(), name="dashboard"),
    path("category/", CategoryView.as_view(), name="category"),
    path('category/<int:pk>',CategoryDetailView.as_view()),
    path("courses/", CourseView.as_view(), name="courses"),
    path("add-course/", AddCourse.as_view(), name="addcourse"),
    path("edit-course/<int:pk>", EditCourse.as_view(), name="editcourse"),
    path("make-inactive/<int:pk>", CourseMakeInactive.as_view(), name="makeinactive"),
    path("add-modules/<int:pk>", AddModules.as_view(), name="addmodule"),
    # path("add-section/", AddSection.as_view(), name="addsection"),
    path("section/<int:pk>/", SectionView.as_view(), name="section"),
    path("section-detail/<int:pk>", SectionDetailView.as_view(), name="sectiondetail"),
    path("module/<int:pk>", ModuleDetail.as_view(), name="module"),
    path("module-delete/<int:pk>", DeleteModule.as_view(), name="deletemodule"),
    # path("edit-section/<int:pk>",EditSectionView.as_view(),name="editsection"),


    path("add-modules2/<int:pk>", AddModules2.as_view(), name="addmodule2"),
    path("create-payment", CreateClientPayment.as_view(), name="createpayment"),
    path("orders",OrderListView.as_view(),name="orders"),
    path("videos",VideoListView.as_view(),name="videos"),
    path("add-videos",VideoCreateView.as_view(),name="addvideos"),
    path("video-detail/<int:pk>",VideoDetailView.as_view(),name="videodetail"),




#    test
    path('add-section/<int:pk>',AddSectionView.as_view(),name="addsection"),
    path('edit-section/<int:pk>',SectionDetailView.as_view(),name="editsection"),
]

api/urls.py
from django.urls import path, include
from .auth import SignUpView
from .views import (
    CartView,
    WishListView,
    AddWishListItem,
    ClearWishList,
    CourseView,
    CourseDetailView,
    EnrolledCoursesView,
    EnrolledCourseDetailView,
    CategoryView,
)


app_name = "api"

urlpatterns = [
    path("auth/signup/", SignUpView.as_view()),
    path("cart/<int:pk>", CartView.as_view()),
    path("wishlist/<int:pk>", WishListView.as_view()),
    path("add-to-wishlist", AddWishListItem.as_view()),
    path("clear-wishlis/", ClearWishList.as_view()),
    path("courses/", CourseView.as_view()),
    path("course/<str:id>", CourseDetailView.as_view()),
    path("mycourses/", EnrolledCoursesView.as_view()),
    path("enrolled-course/<int:pk>", EnrolledCourseDetailView.as_view()),
    path("categories", CategoryView.as_view())
    # path("add-to-cart/"),
    # path("remove-from-cart/"),
    # path("clear-cart"),
    # path("add-quantity"),
    # path("remove-quantity"),
]

app/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from .auth import (
    SignUpView,
    LoginView,
    Logout,
    RefferView,
    RefferalSignUp,
    ResetPassword,
    SendOTP,
)
from .views import (Index, Home,MakePayment,PaymentSuccessView,SuccessPageView, AboutUsView,
 DiscoverView,ReferEarnView,ContactView,TermsAndConditionsView,PrivacyPolicyView)
from .common import ComingSoon

app_name = "app"


urlpatterns = [
    path("sign-up/", SignUpView.as_view(), name="signup"),
    path("sign-up/<str:code>", RefferalSignUp.as_view(), name="refferal_signup"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", Logout, name="logout"),
    path("reset-password/", ResetPassword.as_view(), name="reset-password"),
    path("", Index.as_view(), name="index"),
    path("home/", Home.as_view(), name="home"),
    path("invite/", RefferView.as_view(), name="invite"),
    path("sent-otp/", SendOTP.as_view(), name="sent-otp"),
    # footer links
    path("about-us", AboutUsView.as_view(), name="aboutus"),
    path("refer-and-earn", ReferEarnView.as_view(), name="refer&earn"),
    path("work-from-home", ComingSoon.as_view(), name="workfromhome"),
    path("contact-us", ContactView.as_view(), name="contactus"),
    path("franchisee", ComingSoon.as_view(), name="franchisee"),
    path("terms-and-conditions", TermsAndConditionsView.as_view(), name="termsandconditions"),
    path("privacy-policy", PrivacyPolicyView.as_view(), name="privacypolicy"),
    path("coming-soon", ComingSoon.as_view(), name="comingsoon"),
    path("discover", DiscoverView.as_view(), name="discover"),

    
    path('checkout/<str:id>', MakePayment.as_view(), name="checkout"),
    path("payment-success-no-auth", PaymentSuccessView.as_view(), name="payment-success"),
    path("payment-success/<str:id>",SuccessPageView.as_view(),name="success"),



]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from .settings import MEDIA_ROOT, MEDIA_URL
from django.conf.urls.static import static
from app.email import send_registration_confirm_mail





urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("app.urls", namespace="app")),
    path("adminapp/", include("adminapp.urls", namespace="adminapp")),
    path("courses/", include("courses.urls", namespace="courses")),
    path("", include("cart.urls", namespace="cart")),
    path("api/v1/", include("api.urls", namespace="api")),
    path("api/v1/auth/", include("drf_social_oauth2.urls", namespace="drf")),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

adminapp/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404
from django.views import View
from .utils import create_thumbnail
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.mixins import LoginRequiredMixin
from courses.models import Course, Category, Module, Section, S3VideoUpload
from app.models import Trainer
from PIL import Image
from django.http import JsonResponse
from django.core import serializers
from django.views.decorators.csrf import csrf_exempt
from .models import *
from django.contrib.auth.mixins import PermissionRequiredMixin
from .permissions import *
from .mixins import StaffUserRequiredMixin
from django.conf import settings
from django.core.files.storage import FileSystemStorage


class AdminLogin(View):
    template_name = "adminapp/login.html"
    next_url = None

    def get_next_url(self, request):
        r_params = request.headers["Referer"].split("=")
        try:
            next_url = r_params[1]
            if next_url:
                self.next_url = str(next_url)
        except IndexError:
            self.next_url = None

    def get(self, request):
        print(request.GET.getlist("next"))
        return render(request, self.template_name)

    def post(self, request):
        self.get_next_url(request)
        email = request.POST["email"]
        password = request.POST["password"]
        remember_me = request.POST.get("remember-me", None)
        cred = {"email": email, "password": password}
        for key, value in cred.items():
            if len(value) < 0:
                messages.add_message(
                    request, messages.WARNING, f"{key} should not be empty"
                )
                return redirect("adminapp:login")
            user = authenticate(email=email, password=password)
            if user and user is not None:
                login(request, user)
                session_expiry = 0
                if remember_me is not None:
                    session_expiry = 1209600
                request.session.set_expiry(session_expiry)
                if user.is_staff:
                    if self.next_url is not None:
                        return redirect(self.next_url)
                    return redirect("adminapp:dashboard")
            messages.add_message(request, messages.ERROR, "Wrong credentials.")
            return redirect("adminapp:login")


class DashBoard(LoginRequiredMixin,StaffUserRequiredMixin, View):
    template_name = "adminapp/dashboard.html"
    login_url = "adminapp:login"
    redirect_field_name = "next"

    def get(self, request):
        return render(request, self.template_name)
    

class CategoryView(LoginRequiredMixin,StaffUserRequiredMixin, View):
    template_name = "adminapp/categories.html"
    login_url = "adminapp:login"
    redirect_field_name = "next"
    # raise_exception = True

    def get(self, request):
        cat = Category.objects.all()
        context = {"categories": cat}
        return render(request, self.template_name, context)

    def post(self, request):
        name = request.POST["category"]
        category = Category.objects.create(name=name, created_by=request.user)
        return redirect("adminapp:category")

class CategoryDetailView(LoginRequiredMixin,StaffUserRequiredMixin, View):
    login_url = "adminapp:login"

    def delete(self, request, pk):
        obj = get_object_or_404(Category, id=pk)
        obj.delete()
        return JsonResponse(data={},status=200,safe=False)


class CourseView(LoginRequiredMixin, View):
    template_name = "adminapp/courselist.html"
    login_url = "adminapp:login"
    redirect_field_name = "next"

    def get(self, request):
        courses = Course.objects.all()
        context = {"courses": courses}
        return render(request, self.template_name, context)


class AddCourse(LoginRequiredMixin, StaffUserRequiredMixin,View):
    login_url = "adminapp:login"
    redirect_field_name = "next"
    template_name = "adminapp/add-courses.html"

    def get(self, request):
        cats = Category.objects.all()
        trainers = Trainer.objects.all()
        context = {"category": cats, "trainers": trainers}
        return render(request, self.template_name, context)

    def post(self, request):
        name = request.POST["name"]
        price = request.POST["price"]
        offer_price = request.POST["offer-price"]
        trainer = Trainer.objects.get(id=int(request.POST["trainer"]))
        category = Category.objects.get(id=int(request.POST["category"]))
        description = request.POST["description"]
        image = request.FILES["featured-img"]
        course = Course.objects.create(
            name=name,
            price=price,
            offer_price=offer_price,
            trainer=trainer,
            description=description,
            course_image=image,
            created_by=request.user,
            category=category,
        )
        course.save_thumbnail
        return redirect("adminapp:addmodule", course.id)


class EditCourse(LoginRequiredMixin,StaffUserRequiredMixin, View):
    login_url = "adminapp:login"
    redirect_field_name = "next"
    template_name = "adminapp/edit-course.html"

    def get(self, request, pk):
        course = get_object_or_404(Course, id=pk)
        context = {"course": course, "status_options": Course.STATUS_CHOICE}
        return render(request, self.template_name, context)

    def post(self, request, pk):
        course = get_object_or_404(Course, id=pk)
        course.name = request.POST.get("name", course.name)
        course.price = request.POST.get("price", course.price)
        course.offer_price = request.POST.get("offer-price", course.offer_price)
        course.category = Category.objects.get(
            id=request.POST.get("category", course.category.id)
        )
        course.status = request.POST.get("status", course.status)
        course.trainer = Trainer.objects.get(
            id=request.POST.get("trainer", course.trainer.id)
        )
        course.status = request.POST.get("status", course.status)

        course.description = request.POST.get("description", course.description)
        if request.FILES:
            course.course_image = request.FILES.get("featured-img")
        course.status = course.status
        course.save()
        course.save_thumbnail
        return redirect("adminapp:editcourse", course.id)


class CourseMakeInactive(LoginRequiredMixin,StaffUserRequiredMixin, View):
    login_url = "adminapp:login"

    def get(self, request, pk):
        course = get_object_or_404(Course, id=pk)
        course.status = "INACTIVE"
        course.save()
        return redirect("adminapp:courses")


class AddModules(LoginRequiredMixin,StaffUserRequiredMixin, View):
    login_url = "adminapp:login"
    redirect_field_name = "next"
    template_name = "adminapp/add-modules.html"

    def get(self, request, pk):
        course = get_object_or_404(Course.objects.prefetch_related(), id=pk)
        context = {"course": course, "types": Section.TYPE_CHOICES,'hosts':Section.VIDEO_HOST_CHOICES}
        return render(request, self.template_name, context)

    def post(self, request, pk):
        course = get_object_or_404(Course, id=request.POST["pk"])
        Module.objects.create(
            course=course, title=request.POST["name"], created_by=request.user
        )
        return HttpResponse(status=201)


class AddModules2(LoginRequiredMixin,StaffUserRequiredMixin, View):
    login_url = "adminapp:login"
    redirect_field_name = "next"
    template_name = "adminapp/add-modules2.html"

    def get(self, request, pk):
        course = get_object_or_404(Course.objects.prefetch_related(), id=pk)
        context = {"course": course, "types": Section.TYPE_CHOICES}
        return render(request, self.template_name, context)

    

class AddSection(LoginRequiredMixin, StaffUserRequiredMixin,View):
    login_url = "adminapp:login"
    
    @method_decorator(csrf_exempt)
    def post(self, request):
        print(request.POST)
        module = get_object_or_404(Module, id=request.POST["module_id"])
        section_type = request.POST["section-type"]
        
        video_link = request.POST['video-link'] if section_type == "VIDEO_LINK" else None
        content = request.POST.get("section-content",[])
        section = Section.objects.create(
            title=request.POST["section-name"],
            content_type=section_type,
            content=content,
            module=module,
            video_link=video_link
        )
        data = {"module_id": module.id, "section": section.title}
        return JsonResponse(status=201, data=data, safe=False)


class SectionView(LoginRequiredMixin, StaffUserRequiredMixin,View):
    login_url = "adminapp:login"

    @method_decorator(csrf_exempt)
    def get(self, request, pk):
        get_object_or_404(Section, id=pk).delete()
        return HttpResponse(status=201)


class SectionDetailView(LoginRequiredMixin, StaffUserRequiredMixin,View):
    login_url = "adminapp:login"

    def get(self, request, pk):
        section = get_object_or_404(Section, id=pk)
        return JsonResponse(data=serializers.serialize("json", [section]), safe=False)

    def post(self, request, pk):
        section = get_object_or_404(Section, id=pk, module__created_by=request.user)
        section.title = request.POST.get("section-name", section.title)
        section.content_type = request.POST.get("section-type", section.content_type)
        section.content = request.POST.get("section-content", section.content)
        section.save()
        return JsonResponse(data=serializers.serialize("json", [section]), safe=False)


class EditSectionView(LoginRequiredMixin,StaffUserRequiredMixin, View):
    login_url = "adminapp:login"

adminapp/templates/adminapp/commisions.html
{% extends 'adminapp/dashboard.html' %}
{% load static %}
{% block dashboard %}

<div class="d-flex flex-wrap">
    <div class="col-6 py-5 bg-success"></div>
    <div class="col-6"></div>
    <div class="col-6"></div>
    <div class="col-6"></div>
</div>
{% endblock %}

adminapp/templates/adminapp/create-payments.html
{% extends 'adminapp/dashboard.html' %}
{% load static %}
{% block dashboard %}

<div class="container-fluid p-4">
    <!-- <label for="" class="header-title">ADD PRODUCT</label> -->
    <div class="page-card mt-3">
        <div class="page-card__header border-bottom pb-2 d-flex flex-wrap align-items-center justify-content-between">
            <label for="" class="page-card__title mb-3 mb-sm-0">Create payment Link</label>
        </div>
        <form action="{% url 'adminapp:createpayment' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="d-flex flex-wrap align-items-start justify-content-center add-product">

                <div class="col order-md-2 order-1">
                    <div class="d-flex flex-wrap">
                        <div class="form-group my-3 col-xl-4 col-lg-3 col-md-6 col-12">
                            <label>Client Name</label>
                            <input type="text" class="form-control" name="client" required />
                        </div>
                        <div class="form-group my-3 col-xl-4 col-lg-3 col-md-6 col-12">
                            <label>Phone</label>
                            <input type="number" class="form-control" name="phone" required />
                        </div>
                        <div class="form-group my-3 col-xl-4 col-lg-3 col-md-6 col-12">
                            <label>email</label>
                            <input type="email" class="form-control" name="email" required />
                        </div>
                        <!-- <div class="form-group my-3 col-xl-4 col-lg-3 col-md-6 col-12">
                            <label>Price</label>
                            <input type="number" class="form-control" name="price" />
                        </div> -->
                        <div class="form-group my-3 col-xl-4 col-lg-3 col-md-6 col-12">
                            <label>Offer Price</label>
                            <input type="number" class="form-control" name="offer-price" required />
                        </div>
                        <div class="form-group my-3 col-xl-4 col-lg-3 col-md-6 col-12">
                            <label>Course</label>
                            <select class="form-control" name="course" required>
                                <option value="">-----</option>
                                {% for c in courses %}
                                <option value={{c.id}}>{{c.name}}</option>
                                {% endfor %}

                            </select>
                        </div>
                        <!-- <div class="form-group my-3 col-xl-4 col-lg-3 col-md-6 col-12">
                            <label>Category</label>
                            <select class="form-control" name="category" required>
                                <option value="">-----</option>

                            </select>
                        </div> -->
                        <div class="form-group my-3 col-6">
                            <label for="exampleFormControlTextarea1">Address</label>
                            <textarea class="form-control" rows="3" name="address"></textarea>
                        </div>
                        <div class="form-group my-3 col-6">
                            <label for="exampleFormControlTextarea1">Remarks</label>
                            <textarea class="form-control" rows="3" name="remarks"></textarea>
                        </div>
                    </div>
                </div>
                <div class="add-product__control col-12 order-3 my-3 text-right">
                    <button type="submit" class="btn bg-main text-white mr-3">
                        Save
                    </button>
                    <a class="btn mr-3" href="{% url 'adminapp:orders' %}">
                        Cancel
                    </a>
                </div>
            </div>
        </form>
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                {% endfor %}
        </ul>
        {% endif %}
    </div>
</div>

{% endblock %}

adminapp/templates/adminapp/dashboard.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% block main %}

<div class="container-fluid px-0">
    <div class="row m-0">
        <div class="col-12 px-0 top-bar-container">
            <!-- Top Navigation -->
            <div id="top-bar" class="container-fluid top-bar px-0">
                <div class="d-flex align-items-center justify-content-between h-100">
                    <div class="top-bar__control-button ml-3 col pr-0">
                        <button class="btn bg-0 text-main" onclick="sideBar()"><i class="fas fa-bars"></i></button>
                    </div>
                    <div class="top-bar__user-control col d-flex align-items-center">
                        <div class="form-group top-bar__user-control--search-box mb-0">
                            <input type="text" class="form-control" id="search" placeholder="Type the keyword">
                            <i class="fas fa-search pointer"></i>
                        </div>
                        <div class="top-bar__user-control--profile dropdown">
                            <img src="{% static 'assets/man.png' %}" alt="" class="pointer dropdown-toggle"
                                type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true"
                                aria-expanded="false">
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item" href="#">Edit Profile</a>
                                <a class="dropdown-item" href="#">Logout</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Top Navigation Ends -->
        </div>
        <div id="side-bar-container" class="col-4 side-bar-container px-0 position-relative">
            <!-- Side menu bar -->
            <div id="sidebar-menu" class="container-fluid sidemenu-bar px-0">
                <div class="sidemenu-bar__logo-holder">
                    <img src="{% static 'assets/logo_1589698236logo (1).png' %}" alt="">
                </div>
                <button id="close-btn" class="btn-close d-none pointer" onclick="sideBar()"><i
                        class="fas fa-times"></i></button>
                <div class="sidemenu-bar__menu">
                    <ul class="uk-nav-parent-icon" uk-nav>
                        <li class="uk-active"><a class="nav-link active" href="#"><i
                                    class="fas fa-home mr-3"></i>Dashboard</a></li>
                        <li>
                            <a class="nav-link" href="{% url 'adminapp:courses' %}"><i
                                    class="fas fa-box mr-3"></i>Courses</a>
                        </li>
                        <li>
                            <a class="nav-link" href="{% url 'adminapp:category' %}"><i
                                    class="fas fa-box mr-3"></i>Categories</a>
                        </li>
                        <!-- <li class="uk-parent">
                            <a class="nav-link" href="#"><i class="fas fa-box mr-3"></i>Courses</a>
                            <ul class="uk-nav-sub">
                                <li>
                                    <a class="nav-link" href="#">Category</a>
                                </li>
                                <li>
                                    <a class="nav-link" href="#">Sub Category</a>
                                </li>
                                <li>
                                    <a class="nav-link" href="#">Product List</a>
                                </li>
                                <li>
                                    <a class="nav-link" href="#">Add Product</a>
                                </li>
                            </ul>
                        </li> -->
                        <li class="uk-parent">
                            <a class="nav-link" href="#"><i class="fas fa-dollar-sign mr-3"></i>Sales</a>
                            <ul class="uk-nav-sub">
                                <li>
                                    <a class="nav-link" href="{% url 'adminapp:orders' %}">Orders</a>
                                    <a class="nav-link" href="{% url 'adminapp:createpayment' %}">Create Order</a>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <a class="nav-link" href="{% url 'adminapp:videos' %}"><i
                                    class="far fa-image mr-3"></i>Videos</a>
                        </li>
                        <li>
                            <a class="nav-link" href="#"><i class="fas fa-user mr-3"></i>Customers</a>
                        </li>
                        <li class="uk-parent">
                            <a class="nav-link" href="#"><i class="fas fa-file-alt mr-3"></i>Report</a>
                            <ul class="uk-nav-sub">
                                <li>
                                    <a class="nav-link" href="#">Product Report</a>
                                </li>
                                <li>
                                    <a class="nav-link" href="#">Sales Report</a>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <a class="nav-link" href="#"><i class="fas fa-file-invoice-dollar mr-3"></i>Invoice</a>
                        </li>
                        <li id="logout">
                            <a class="nav-link"><i class="fas fa-power-off mr-3"></i>Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
            <!-- Side menu bar Ends -->
        </div>
        <div class="col content-container px-0">
            <div class="content-wraper">
                {% block dashboard %}
                {% endblock %}
                <div class="spacer"></div>
                <!-- footer -->
                <div class="container-fluid bg-white footer-credits p-4">
                    <div class="d-flex flex-wrap w-100">
                        <label for="" class="mb-0 col-md-6 col-12 text-md-left text-center">Copyright 2019 © School Of
                            Resourses All
                            rights reserved.</label>
                        <label class="col-md-6 col-12 mb-0 text-md-right text-center" for="">Hand crafted & made with
                            <br class="d-block d-md-none"> <i class="fas fa-heart"></i></label>
                    </div>
                </div>
                <!-- footer ends -->
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    document.addEventListener('DOMContentLoaded', function () {
        document.getElementById('logout').addEventListener('click', logout);
    });
    function logout() {
        const xhr = new XMLHttpRequest();
        xhr.open('GET', '/logout/', true)
        xhr.send();
        xhr.onreadystatechange = function () {
            if (this.readyState === XMLHttpRequest.DONE && this.status === 200) window.location.reload()
        };
    };
</script>
{% endblock %}

adminapp/templates/adminapp/editor.html
<div>
    <div id="node"></div>
    <div id="editor"></div>
</div>
<script src="https://cdn.jsdelivr.net/npm/editorjs-html@3.0.3/build/edjsHTML.browser.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@editorjs/editorjs@latest"></script>
<script src="https://cdn.jsdelivr.net/npm/@editorjs/header@latest"></script>
<script src="https://cdn.jsdelivr.net/npm/@editorjs/link@latest"></script>
<script src="https://cdn.jsdelivr.net/npm/@editorjs/list@latest"></script>
<script src="https://cdn.jsdelivr.net/npm/@editorjs/embed@latest"></script>
<script src="https://cdn.jsdelivr.net/npm/@editorjs/raw"></script>
<script src="https://cdn.jsdelivr.net/npm/@editorjs/simple-image@latest"></script>
<script src="https://cdn.jsdelivr.net/npm/@editorjs/quote@latest"></script>
<script>
    const editor = new EditorJS({
            autofocus: true,
            holder: 'editor',
            tools: {
                header: {
                    class: Header,
                },
                linkTool: {
                    class: LinkTool,
                    config: {
                        endpoint: "https://source.unsplash.com/random"
                    }
                },
                list: {
                    class: List,
                    inlineToolBar: true
                }
                ,embed: {
                    class: Embed,
                    config: {
                        services: {
                            youtube: true
                        }
                    }
                }, 
                image: {
                    class: SimpleImage
                },
                quote: Quote
            },
        });
</script>

adminapp/templates/adminapp/share-payment-link.html
{% extends 'adminapp/dashboard.html' %}
{% load static %}
{% block dashboard %}

{% endblock %}

adminapp/templates/adminapp/videos.html
{% extends 'adminapp/dashboard.html' %} {% load static %}
{% load custom_tags %} {% block dashboard %}

<div class="container-fluid p-4">
    <label for="" class="header-title">Videos</label>
    <div class="page-card mt-3">
        <div class="page-card__header border-bottom pb-2 d-flex flex-wrap align-items-center justify-content-between">
            <label for="" class="page-card__title mb-3 mb-sm-0">Order List</label>
            <a href="{% url 'adminapp:addvideos' %}"><button class="btn btn-danger">Add Video</button></a>
        </div>
        <table class="uk-table" id="video_table">
            <caption></caption>
            <thead>
                <tr>
                    <th class="uk-text-bold">Sl No</th>
                    <th class="uk-text-bold">Video Name</th>
                    <th class="uk-text-bold">URL</th>
                    <th class="uk-text-bold">Status</th>
                    <th class="uk-text-bold">Uploaded At</th>
                    <th class="uk-text-bold">Actions</th>


                </tr>
            </thead>

            <tbody>
                {% for video in video_files %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td>{{video.name}}</td>
                    <td>{% spilt_signature video.file.url %}</td>
                    <td>{{video.is_active}}</td>
                    <td>{{video.uploaded_at}}</td>
                    <td><a href="{% url 'adminapp:videodetail' video.id %}" target="_blank">
                            <i class="far fa-edit text-info pointer"></i>
                        </a></td>

                </tr>
                {% endfor %}
            </tbody>
        </table>

        <!--  ends -->
    </div>
</div>
</div>
{% block script %}
<script>
    $(document).ready(function () {
        $('#video_table').DataTable();
    });
</script>
{% endblock script %}

{% endblock %}