api/urls.py
from django.urls import path, include
from .auth import SignUpView
from .views import (
    CartView,
    WishListView,
    AddWishListItem,
    ClearWishList,
    CourseView,
    CourseDetailView,
    EnrolledCoursesView,
    EnrolledCourseDetailView,
    CategoryView,
)


app_name = "api"

urlpatterns = [
    path("auth/signup/", SignUpView.as_view()),
    path("cart/<int:pk>", CartView.as_view()),
    path("wishlist/<int:pk>", WishListView.as_view()),
    path("add-to-wishlist", AddWishListItem.as_view()),
    path("clear-wishlis/", ClearWishList.as_view()),
    path("courses/", CourseView.as_view()),
    path("course/<str:id>", CourseDetailView.as_view()),
    path("mycourses/", EnrolledCoursesView.as_view()),
    path("enrolled-course/<int:pk>", EnrolledCourseDetailView.as_view()),
    path("categories", CategoryView.as_view())
    # path("add-to-cart/"),
    # path("remove-from-cart/"),
    # path("clear-cart"),
    # path("add-quantity"),
    # path("remove-quantity"),
]

app/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from .auth import (
    SignUpView,
    LoginView,
    Logout,
    RefferView,
    RefferalSignUp,
    ResetPassword,
    SendOTP,
)
from .views import (Index, Home,MakePayment,PaymentSuccessView,SuccessPageView, AboutUsView,
 DiscoverView,ReferEarnView,ContactView,TermsAndConditionsView,PrivacyPolicyView)
from .common import ComingSoon

app_name = "app"


urlpatterns = [
    path("sign-up/", SignUpView.as_view(), name="signup"),
    path("sign-up/<str:code>", RefferalSignUp.as_view(), name="refferal_signup"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", Logout, name="logout"),
    path("reset-password/", ResetPassword.as_view(), name="reset-password"),
    path("", Index.as_view(), name="index"),
    path("home/", Home.as_view(), name="home"),
    path("invite/", RefferView.as_view(), name="invite"),
    path("sent-otp/", SendOTP.as_view(), name="sent-otp"),
    # footer links
    path("about-us", AboutUsView.as_view(), name="aboutus"),
    path("refer-and-earn", ReferEarnView.as_view(), name="refer&earn"),
    path("work-from-home", ComingSoon.as_view(), name="workfromhome"),
    path("contact-us", ContactView.as_view(), name="contactus"),
    path("franchisee", ComingSoon.as_view(), name="franchisee"),
    path("terms-and-conditions", TermsAndConditionsView.as_view(), name="termsandconditions"),
    path("privacy-policy", PrivacyPolicyView.as_view(), name="privacypolicy"),
    path("coming-soon", ComingSoon.as_view(), name="comingsoon"),
    path("discover", DiscoverView.as_view(), name="discover"),

    
    path('checkout/<str:id>', MakePayment.as_view(), name="checkout"),
    path("payment-success-no-auth", PaymentSuccessView.as_view(), name="payment-success"),
    path("payment-success/<str:id>",SuccessPageView.as_view(),name="success"),



]

courses/urls.py
from django.urls import path
from .views import (
    CourseView,
    CourseDetailView,
    EnrolledCourseDetail,
    GetEnrolled,
    SectionStatusUpdate,
    LoadSection,
    LoadNextSection,
    LoadPreviousSection,
)
from .payment import BuyCourse, PaymentSuccess, BuyShareDCourse
from .share import ShareProduct, ProdcutDetailView

app_name = "courses"

urlpatterns = [
    path("courses/", CourseView.as_view(), name="coursesall"),
    path("course-detail/<str:id>/", CourseDetailView.as_view(), name="detail"),
    path("continue-course/<str:id>/", EnrolledCourseDetail.as_view(), name="continue"),
    path("enroll-course/", GetEnrolled.as_view(), name="enrollcourse"),
    path("update-status/", SectionStatusUpdate.as_view(), name="updatestatus"),
    path("load-section/", LoadSection.as_view(), name="loadsection"),
    path("load-next-section/", LoadNextSection.as_view(), name="nextsection"),
    path("load-previous-section/", LoadPreviousSection.as_view(), name="loadprevious"),
    path("checkout/<str:id>", BuyCourse.as_view(), name="checkout"),
    path(
        "checkout/<str:id>/<str:share_link>", BuyShareDCourse.as_view(), name="checkout"
    ),
    path("payment-success/", PaymentSuccess.as_view(), name="success"),
    path("share/<str:uid>", ShareProduct.as_view(), name="share"),
    path("course/<str:id>", ProdcutDetailView.as_view(), name="product"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from .settings import MEDIA_ROOT, MEDIA_URL
from django.conf.urls.static import static
from app.email import send_registration_confirm_mail





urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("app.urls", namespace="app")),
    path("adminapp/", include("adminapp.urls", namespace="adminapp")),
    path("courses/", include("courses.urls", namespace="courses")),
    path("", include("cart.urls", namespace="cart")),
    path("api/v1/", include("api.urls", namespace="api")),
    path("api/v1/auth/", include("drf_social_oauth2.urls", namespace="drf")),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

courses/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Course, Section, Enrollment
from django.http import JsonResponse, Http404
from django.core import serializers
import json
from django.core.exceptions import ValidationError


class CourseView(View):
    template_name = "courses.html"

    def get(self, request):
        courses = Course.objects.filter(status="ACTIVE")
        context = {"courses": courses}
        return render(request, self.template_name, context)


class CourseDetailView(View):
    template_name = "course-detail.html"
    base_url = ""
    host = ""

    def get(self, request, id):
        self.host = request.headers["Host"]
        self.base_url = f"https://{self.host}"
        try:
            course = get_object_or_404(Course, uid=id)
            if request.user.is_authenticated:
                en = Enrollment.objects.get(user=request.user, course=course)
                is_enrolled = True
            else:
                en = {}
                is_enrolled = False
        except Enrollment.DoesNotExist:
            is_enrolled = False
            en = {}

        except ValidationError:
            raise Http404()

        context = {
            "course": course,
            "is_enrolled": is_enrolled,
            "en": en,
            "page_title": course.name,
            "webmaster": {
                "url": f"{self.base_url}/courses/course-detail/{course.uid}/",
                "title": course.name,
                "description": course.description,
                "image_url": f"{self.base_url}{course.course_image.url}",
            },
        }
        return render(request, self.template_name, context)


class GetEnrolled(LoginRequiredMixin, View):
    login_url = "app:login"

    def post(self, request):
        user = request.user
        course = Course.objects.prefetch_related("modules").get(
            id=request.POST.get("course_id")
        )
        try:
            obj = Enrollment.objects.get(user=user, course=course)
        except Enrollment.DoesNotExist:
            data = []
            for module in course.modules.all():
                for section in module.sections.all():
                    data.append({"id": section.id, "is_completed": False})
            obj = Enrollment.objects.create(user=user, course=course, sections=data)
        res = {"enrollment_id": obj.id}
        return JsonResponse(status=201, data=res, safe=False)


class EnrolledCourseDetail(LoginRequiredMixin, View):
    login_url = "app:login"
    template_name = "enrolled-course-detail.html"

    def get(self, request, id):
        try:
            obj = get_object_or_404(Enrollment, uid=id, user=request.user)
            course = obj.course
            matching_sections = list(obj.sections)
            module_data = []
            for module in course.modules.all():
                data = {"id": module.id, "title": module.title}
                sections = []
                for section in module.sections.all():
                    try:
                        match = list(
                            filter(lambda x: (x["id"] == section.id), matching_sections)
                        )[0]
                        sections.append(
                            {
                                "id": section.id,
                                "title": section.title,
                                "is_completed": match["is_completed"],
                                "content_type": section.content_type,
                            }
                        )
                    except IndexError:
                        obj.sections.append({"id": section.id, "is_completed": False})
                        sections.append(
                            {
                                "id": section.id,
                                "title": section.title,
                                "is_completed": False,
                                "content_type": section.content_type,
                            }
                        )

                module_data.append({**data, "sections": sections})
            try:
                _section = Section.objects.get(id=obj.last_viewed_section)
                last_viewed_section = {
                    "id": _section.id,
                    "title": _section.title,
                    "content_type": _section.content_type,
                    "content": _section.content,
                }
            except Section.DoesNotExist:
                try:

                    last_viewed_section = module_data[0]["sections"][0]
                    obj.last_viewed_section = last_viewed_section["id"]
                except:
                    last_viewed_section = 0
                    obj.last_viewed_section = 0
            obj.save()
            context = {
                "course": obj.course,
                "enrolled_course": module_data,
                "enrollment_id": obj.id,
                "last_viewed_section": json.dumps(last_viewed_section),
                "total_number_of_sections": len(module_data),
                # "progress": obj.get_progress,
            }
            return render(request, self.template_name, context)
        except Enrollment.DoesNotExist:
            raise Http404()


class SectionStatusUpdate(LoginRequiredMixin, View):
    login_url = "app:login"

    def post(self, request):
        print(request.POST)
        section_id = request.POST["section_id"]
        obj = get_object_or_404(Enrollment, id=request.POST["enrollment_id"])
        section = list(filter(lambda x: x["id"] == int(section_id), obj.sections))
        try:
            s = section[0]
            index = obj.sections.index(s)
            s["is_completed"] = not s["is_completed"]
            obj.sections[index] = s
            obj.save()
        except IndexError:
            JsonResponse(status=400, data={})
        return JsonResponse(data={"is_completed": True})


class LoadSection(LoginRequiredMixin, View):
    login_url = "app:login"

    def post(self, request):
        enrollment = get_object_or_404(Enrollment, id=request.POST["enrollment_id"])
        section = get_object_or_404(Section, id=request.POST["section_id"])
        enrollment.last_viewed_section = section.id
        current_section = list(
            filter(
                lambda x: x["id"] == enrollment.last_viewed_section, enrollment.sections
            )
        )[0]
        index = enrollment.sections.index(current_section)
        current_section["is_completed"] = True
        enrollment.sections[index] = current_section
        enrollment.save()
        data = {
            "id": section.id,
            "title": section.title,
            "content_type": section.content_type,
            "content": section.content,
            "video_link":section.video_link
        }
        return JsonResponse(data=data, safe=False)


class LoadNextSection(LoginRequiredMixin, View):
    login_url = "app:login"

    def post(self, request):
        en = get_object_or_404(Enrollment, id=request.POST["enrollment_id"])
        current_section = Section.objects.get(id=en.last_viewed_section)
        course = en.course
        sections_list = []
        for m in course.modules.all():
            for s in m.sections.all():
                sections_list.append(s)
        index = sections_list.index(current_section)
        length_of_sections = len(sections_list)
        if (index + 1) < length_of_sections:
            next_section = sections_list[index + 1]
        else:
            next_section = sections_list[length_of_sections - 1]
        try:
            match = list(filter(lambda x: x["id"] == next_section.id, en.sections))[0]
        except IndexError:
            en.sections.append({"id": next_section.id, "is_completed": True})
        data = {
            "id": next_section.id,
            "title": next_section.title,
            "is_completed": True,
            "content": next_section.content,
            "content_type": next_section.content_type,
        }
        en.last_viewed_section = next_section.id
        en.save()
        return JsonResponse(data=data, safe=False)


class LoadPreviousSection(LoginRequiredMixin, View):
    login_url = "app:login"

    def post(self, request):
        en = get_object_or_404(Enrollment, id=request.POST["enrollment_id"])
        current_section = Section.objects.get(id=en.last_viewed_section)
        course = en.course
        sections_list = [] 
        for m in course.modules.all():
            for s in m.sections.all():
                sections_list.append(s)
        index = sections_list.index(current_section)
        if index != 0:
            previous_section = sections_list[index - 1]
        else:
            previous_section = sections_list[0]
        try:
            match = list(filter(lambda x: x["id"] == previous_section.id, en.sections))[
                0
            ]
        except IndexError:
            en.sections.appned({"id": previous_section.id, "is_completed": True})
        data = {
            "id": previous_section.id,
            "title": previous_section.title,
            "is_completed": True,
            "content": previous_section.content,
            "content_type": previous_section.content_type,
        }
        en.last_viewed_section = previous_section.id
        en.save()
        return JsonResponse(data=data, safe=False)

courses/templates/checkout-no-login.html
{% extends "main.html" %}
{% load static %}
{% block main %}
<div x-data="App()" x-show="isLoading" x-on:load.window="isLoading = $event.detail.isLoading">
    <div id="loader"
        class="container-fluid vh-100 w-100 d-flex align-items-center justify-content-center overlay-black">
        <svg class="spinner" viewBox="0 0 66 66" xmlns="http://www.w3.org/2000/svg">
            <circle class="path" fill="none" stroke-width="6" stroke-linecap="round" cx="33" cy="33" r="30"></circle>
        </svg>
    </div>
</div>



<div x-data="App()" x-init="init()" class="container-fluid p-md-4">
    <div class="container py-5 px-md-3 px-0">
        <div class="row">
            <div class="col-md">

                <label for="" class="page-card__title mb-2">Order details</label>
                <div class="d-flex flex-wrap align-items-center justify-content-between course-order">
                    <img src="{{course.course_thumbnail.url}}" width="100" height="80" class="course-order__tumbnail"
                        alt="">
                    <label class="course-order__title col " for="">{{course.name}}</label>
                    <span class="course-order__price">
                        <span>{{payment.offer_price}}</span>
                        <br>
                        <span class="text-secondary"><del>

                                {{course.price}}

                            </del></span>
                    </span>
                </div>
            </div>
            <div class="col-md-5">
                <div class="check-price__details">
                    <label for="" class="page-card__title mb-sm-0">Summary</label>

                    <div class="d-flex flex-wrap justify-content-between w-100 py-2 mt-3">
                        <span class="text__checkout">Original Price</span>
                        <span class="text__checkout">{{course.price}}</span>
                    </div>
                    <div class="d-flex flex-wrap justify-content-between w-100 pt-2">
                        <span class="text__checkout"> Discount</span>
                        <span class="text__checkout">
                            {% if discount %}
                            {{discount}}
                            {% else %}
                            {{course.offer_price}}
                            {% endif %}
                        </span>
                    </div>
                    <hr class="mb-2">
                    <div class="d-flex flex-wrap justify-content-between w-100 pt-1">
                        <span class="font-weight-bold text__checkout">Total</span>
                        <span class="text__checkout">
                            {{total}}
                        </span>
                    </div>
                    <div class="d-flex flex-wrap justify-content-between w-100 pt-1">
                        <!-- <p class="text__checkout mt-3">
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquam sapiente delectus
                            assumenda.
                        </p> -->
                        <p class="text__checkout py-3">
                            by purchasing you agreeing our <span class="font-weight-normal text-info">Terms &
                                service</span>
                        </p>
                    </div>
                    <button x-on:click="makeCheckout(event);" id=checkout-btn class="btn btn-main w-100">Complete
                        Payment</button>
                </div>
            </div>
        </div>
    </div>
</div>
{% csrf_token %}
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script>
    function App() {
        return {
            isLoading: false,
            currency: "",
            makeCheckout(e) {
                e.preventDefault();
                createLoadEvent(true);
                var paymentData = postData((this.currency));
                paymentData.then(res => res.json()).then(data => {
                    const payment = data.payment;
                    createLoadEvent(false);
                    var options = {
                        "key": payment.rzp_key,
                        "amount": payment.amount,
                        "currency": payment.currency,
                        "name": "School Of Resources",
                        "description": "Test Transaction",
                        "image": "https://schoolofresources.com/static/assets/logo_1589698236logo%20(1).png",
                        "order_id": payment.id,
                        "handler": function (res) {
                            const share_link = '{{share_link}}'
                            const url = "/payment-success-no-auth";
                            const payload = new FormData();
                            if (share_link !== '') {
                                payload.append('share_link', share_link);
                            }
                            payload.append('course_id', '{{course.uid}}')
                            payload.append('payment_id', res.razorpay_payment_id);
                            payload.append('order_id', res.razorpay_order_id);
                            payload.append('signature', res.razorpay_signature);
                            payload.append('csrfmiddlewaretoken', '{{csrf_token}}')
                            payload.append('order', '{{payment.id}}')
                            fetch(url, {
                                method: 'POST',
                                body: payload
                            }).then(res => res.json()).then(data => {
                                const url = data.redirect_url;
                                window.location.replace(url);
                                // window.location.reload();
                            });
                        },
                        "prefill": {
                            "name": "{{payment.client_name}}" || "",
                            "email": "{{payment.email}}" || "",
                            "contact": "{{payment.phone}}" || ""
                        },
                        "notes": {
                            "address": ""
                        }, "theme": { "color": "#F37254" }
                    };
                    var rzp1 = new Razorpay(options);
                    rzp1.open();
                });
            },
            init() {
                var xhr = new XMLHttpRequest();
                xhr.open('GET', "https://freegeoip.app/json/", true);
                xhr.send();
                xhr.onreadystatechange = () => {
                    if (xhr.readyState === XMLHttpRequest.DONE && xhr.status === 200) {
                        const location = JSON.parse(xhr.response);
                        const country = getCountries(location.country_code);
                        country.then(res => res.json()).then(data => {
                            try {
                                const code = data.currencies[0]['code'];
                                if (code === "") {
                                    const currency = "INR";
                                    this.currency = currency;
                                }
                                this.currency = code;
                            } catch (error) {
                                if (error instanceof TypeError) {
                                    const currency = "INR";
                                    this.currency = currency;
                                }
                            }
                        });
                    }
                }
            }
        }
    }

    function createLoadEvent(isLoading) {
        const event = new CustomEvent('load', {
            detail: {
                isLoading: isLoading
            }
        });
        window.dispatchEvent(event);
    }

    async function postData(currency) {
        url = "";
        const payload = new FormData();
        payload.append('csrfmiddlewaretoken', '{{csrf_token}}');
        payload.append('currency', currency);

        const response = await fetch(url, {
            method: 'POST',
            body: payload,
        });
        return response;

    }
    async function getCountries(code) {
        const url = `https://restcountries.eu/rest/v2/alpha/${code}`;
        const res = await fetch(url);
        return res;
    }
    async function getGeoLoation() {
        const url = "https://freegeoip.app/json/";
        const res = await fetch(url, {
            method: 'GET',
            mode: 'cors',
            headers: { "content-type": "application/json", "accept": "application/json", "Access-Control-Allow-Origin": "*" },
        })
        return res;
    };
</script>
{% endblock %}

courses/templates/course-detail.html
{% extends 'main.html' %} {% block main %}

<div class="container-fluid border-bottom">
    <div class="container">
        <div class="course__enroll">
            <label for="" class="course__enroll--name">{{course.name}}</label>
            <label for="" class="mb-0 course__enroll--author"><span class="text-main">Author
                    :</span>{{course.trainer.user.full_name }}</label>
            <h3>Rs. <span style="text-decoration: line-through; font-size:small;">{{course.price}}</span>
            </h3>
            {% if is_enrolled == True %}
            <a href="{% url 'courses:continue' en.uid %}">
                <button class="btn btn-main d-block mt-4">Go to course</button>
            </a>
            {% elif has_share_link == True and is_enrolled == False %}
            <a href="{% url 'courses:checkout' id=course.uid share_link=share_link %}">
                <button class="btn btn-main d-block mt-4" id="enroll-btn">Enroll Now</button>
            </a>
            {% elif is_enrolled == False %}
            <a href="{% url 'courses:checkout' course.uid %}">
                <button class="btn btn-main d-block mt-4" id="enroll-btn">Enroll Now</button>
            </a>
            {% elif has_share_link == True and is_enrolled == True %}
            <a href="{% url 'courses:continue' en.uid %}">
                <button class="btn btn-main d-block mt-4" id="enroll-btn">Go to course</button>
            </a>
            {% endif %}
        </div>
    </div>
</div>

<div class="container-fluid py-4">
    <div class="container pb-5">
        <div class="d-flex flex-wrap">
            <div class="course-structure on-mobile col-12 px-0 mb-4">
                <div class="container-fluid border-bottom py-4">
                    <label class="course-header__title mb-0">Course Content</label>
                </div>
                <div class="container-fluid px-0">
                    <div id="accordion">
                        {% for c in c.modules.all %}
                        <div class="card">
                            <div class="card-header pointer" id="headingOne" data-toggle="collapse"
                                data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                <h5 class="mb-0 w-100 d-flex align-items-center justify-content-between">
                                    <span>
                                        {{c.title}}
                                    </span>
                                    <span class="drop-down" uk-icon="chevron-down"></span>
                                </h5>
                            </div>

                            <div id="collapseOne" class="collapse" aria-labelledby="headingOne"
                                data-parent="#accordion">
                                {% for s in m.sections %}
                                <div class="d-flex w-100 border-bottom p-3 align-items-center justify-content-between">
                                    <div class="form-check">
                                        <!-- <input type="checkbox" class="form-check-input" id="exampleCheck1"> -->
                                        <label class="form-check-label small mb-0 text main" for="exampleCheck1">1.
                                            {{s.title}}</label>
                                    </div>
                                    <span class="drop-down" uk-icon="play-circle"></span>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="col px-0">
                <div class="course__detail">
                    <label class="course__detail--title">What you'll Learn</label>
                    {% for m in course.modules.all %}
                    <label for="" class="course__detail--item">{{m.title}}</label>
                    {% endfor %}
                </div>

                <h2 class="mb-3">Overview</h2>
                <p class="mb-3">
                    {{course.description}}
                </p>
            </div>
            <div class="course-structure col-5 pl-5 on-desktop px-0">
                <div class="container-fluid pb-3">
                    <label class="course-header__title mb-0">Course Content</label>
                </div>
                <div class="container-fluid px-0">
                    <div id="accordion">
                        {% for m in course.modules.all %}
                        <div class="card">
                            <div class="card-header pointer" id="headingOne" data-toggle="collapse"
                                data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                <h5 class="mb-0 w-100 d-flex align-items-center justify-content-between">
                                    <span>
                                        {{m.title}}
                                    </span>
                                    <span class="drop-down" uk-icon="chevron-down"></span>
                                </h5>
                            </div>

                            <div id="collapseOne" class="collapse" aria-labelledby="headingOne"
                                data-parent="#accordion">
                                {% for s in m.sections.all %}
                                <div class="d-flex w-100 border-bottom p-3 align-items-center justify-content-between">
                                    <div class="form-check">
                                        <!-- <input type="checkbox" class="form-check-input" id="exampleCheck1"> -->
                                        <label class="form-check-label small mb-0 text-main" for="exampleCheck1">
                                            {{forloop.counter}}.
                                            {{s.title}} <span class="text-secondary ml-1 small">(5 min.)</span></label>
                                    </div>
                                    <span class="mr-2" uk-icon="play-circle"></span>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
{% csrf_token %}
<script>
    document.addEventListener('DOMContentLoaded', function () {
        const xhr = new XMLHttpRequest();
        const response = getGeoLoation();
        response.then(res => res.json()).then(data => {
            const country = getCountry(data.country_code);
            country.then(res => res.json()).then(data => {
                const currency = data.currencies[0]['code'];
                const btn = document.getElementById('enroll-btn');
                // if (btn !== null) addEventListener('click', enrollCourse(currency));
            })
        })
    });

    function enrollCourse(currency) {
        const payload = new FormData();
        payload.append('course_id', "{{course.id}}");
        payload.append("csrfmiddlewaretoken", "{{csrf_token}}");
        payload.append('currency', currency)
        var xhr = new XMLHttpRequest();
        xhr.open('POST', "/courses/checkout/", true);
        xhr.send(payload);
        // xhr.onreadystatechange = function(){
        //     if(this.readyState === XMLHttpRequest.DONE && this.status === 201){
        //         const response = JSON.parse(this.response)
        //         window.location.replace(`/courses/course/${response['enrollment_id']}/`)
        //     }
        // }
    }
    async function getCountry(code) {
        const url = `https://restcountries.eu/rest/v2/alpha/${code}`;
        const res = await fetch(url);
        return res;
    }
    async function getGeoLoation() {
        const url = "https://freegeoip.app/json/";
        const res = await fetch(url, {
            method: 'GET',
            mode: 'cors',
            cache: 'no-cache',
            credentials: 'same-origin',
            headers: { "content-type": "application/json", "accept": "application/json" },
            referrerPolicy: 'no-referrer'
        })
        return res;
    };
</script>

{% endblock main %}