api/urls.py
from django.urls import path, include
from .auth import SignUpView
from .views import (
    CartView,
    WishListView,
    AddWishListItem,
    ClearWishList,
    CourseView,
    CourseDetailView,
    EnrolledCoursesView,
    EnrolledCourseDetailView,
    CategoryView,
)


app_name = "api"

urlpatterns = [
    path("auth/signup/", SignUpView.as_view()),
    path("cart/<int:pk>", CartView.as_view()),
    path("wishlist/<int:pk>", WishListView.as_view()),
    path("add-to-wishlist", AddWishListItem.as_view()),
    path("clear-wishlis/", ClearWishList.as_view()),
    path("courses/", CourseView.as_view()),
    path("course/<str:id>", CourseDetailView.as_view()),
    path("mycourses/", EnrolledCoursesView.as_view()),
    path("enrolled-course/<int:pk>", EnrolledCourseDetailView.as_view()),
    path("categories", CategoryView.as_view())
    # path("add-to-cart/"),
    # path("remove-from-cart/"),
    # path("clear-cart"),
    # path("add-quantity"),
    # path("remove-quantity"),
]

app/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from .auth import (
    SignUpView,
    LoginView,
    Logout,
    RefferView,
    RefferalSignUp,
    ResetPassword,
    SendOTP,
)
from .views import (Index, Home,MakePayment,PaymentSuccessView,SuccessPageView, AboutUsView,
 DiscoverView,ReferEarnView,ContactView,TermsAndConditionsView,PrivacyPolicyView)
from .common import ComingSoon

app_name = "app"


urlpatterns = [
    path("sign-up/", SignUpView.as_view(), name="signup"),
    path("sign-up/<str:code>", RefferalSignUp.as_view(), name="refferal_signup"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", Logout, name="logout"),
    path("reset-password/", ResetPassword.as_view(), name="reset-password"),
    path("", Index.as_view(), name="index"),
    path("home/", Home.as_view(), name="home"),
    path("invite/", RefferView.as_view(), name="invite"),
    path("sent-otp/", SendOTP.as_view(), name="sent-otp"),
    # footer links
    path("about-us", AboutUsView.as_view(), name="aboutus"),
    path("refer-and-earn", ReferEarnView.as_view(), name="refer&earn"),
    path("work-from-home", ComingSoon.as_view(), name="workfromhome"),
    path("contact-us", ContactView.as_view(), name="contactus"),
    path("franchisee", ComingSoon.as_view(), name="franchisee"),
    path("terms-and-conditions", TermsAndConditionsView.as_view(), name="termsandconditions"),
    path("privacy-policy", PrivacyPolicyView.as_view(), name="privacypolicy"),
    path("coming-soon", ComingSoon.as_view(), name="comingsoon"),
    path("discover", DiscoverView.as_view(), name="discover"),

    
    path('checkout/<str:id>', MakePayment.as_view(), name="checkout"),
    path("payment-success-no-auth", PaymentSuccessView.as_view(), name="payment-success"),
    path("payment-success/<str:id>",SuccessPageView.as_view(),name="success"),



]

courses/urls.py
from django.urls import path
from .views import (
    CourseView,
    CourseDetailView,
    EnrolledCourseDetail,
    GetEnrolled,
    SectionStatusUpdate,
    LoadSection,
    LoadNextSection,
    LoadPreviousSection,
)
from .payment import BuyCourse, PaymentSuccess, BuyShareDCourse
from .share import ShareProduct, ProdcutDetailView

app_name = "courses"

urlpatterns = [
    path("courses/", CourseView.as_view(), name="coursesall"),
    path("course-detail/<str:id>/", CourseDetailView.as_view(), name="detail"),
    path("continue-course/<str:id>/", EnrolledCourseDetail.as_view(), name="continue"),
    path("enroll-course/", GetEnrolled.as_view(), name="enrollcourse"),
    path("update-status/", SectionStatusUpdate.as_view(), name="updatestatus"),
    path("load-section/", LoadSection.as_view(), name="loadsection"),
    path("load-next-section/", LoadNextSection.as_view(), name="nextsection"),
    path("load-previous-section/", LoadPreviousSection.as_view(), name="loadprevious"),
    path("checkout/<str:id>", BuyCourse.as_view(), name="checkout"),
    path(
        "checkout/<str:id>/<str:share_link>", BuyShareDCourse.as_view(), name="checkout"
    ),
    path("payment-success/", PaymentSuccess.as_view(), name="success"),
    path("share/<str:uid>", ShareProduct.as_view(), name="share"),
    path("course/<str:id>", ProdcutDetailView.as_view(), name="product"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from .settings import MEDIA_ROOT, MEDIA_URL
from django.conf.urls.static import static
from app.email import send_registration_confirm_mail





urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("app.urls", namespace="app")),
    path("adminapp/", include("adminapp.urls", namespace="adminapp")),
    path("courses/", include("courses.urls", namespace="courses")),
    path("", include("cart.urls", namespace="cart")),
    path("api/v1/", include("api.urls", namespace="api")),
    path("api/v1/auth/", include("drf_social_oauth2.urls", namespace="drf")),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

app/templates/courses.html
{% extends 'main.html' %} {% load static %}
{% load custom_tags %}
{% block main %}

<!-- Banner -->

<div class="container py-5">
  <div class="row">
    {% if courses %}{% for c in courses %}
    <div class="col-lg-4 col-sm-6 mb-4">
      <a href="{% url 'courses:detail' c.uid %}" class="w-100">

        <div class="course-card">
          <img src="{{ c.course_image.url }}" alt="" class="course-card__img" />
        </div>

      </a>
      <h3 class="mt-3" for="">{{c.name}}</h3>
      <p class="mt-3 text-justify course-card__title">
        {{c.description|truncatechars:150}}
      </p>
      <!-- <a href="{% url 'courses:share' uid=c.uid %}">
        <button class="btn btn-main w-100 mt-4">share</button>  
      </a> -->
      {% if request.user.is_authenticated %}
      <div x-data="App()" class="d-block text-right mt-3">
        <button x-on:click="getLink('{{c.uid}}')" class="btn btn-danger px-3 badge-pill pb-2">
          Share <span class="uk-margin-small-left" uk-icon="social"></span>
        </button>
        <div class="social-share rounded" uk-dropdown="mode: click">
          <div x-show="link_generated && isLoading == false">
            <a x-bind:href="'https://www.facebook.com/sharer/sharer.php?u='+link.link" target="_blank"
              class="uk-icon-button  uk-margin-small-right text-fb" uk-icon="facebook"> </a>
            <a x-bind:href="'https://api.whatsapp.com/send?text='+link.link" target="_blank"
              class="uk-icon-button  uk-margin-small-right text-whatsapp" uk-icon="whatsapp"> </a>
            <a x-bind:href="'https://www.linkedin.com/shareArticle?mini=true&title='+link.title+'&url='+link.link"
              target="_blank" class="uk-icon-button text-linkedin" uk-icon="linkedin"></a>
            <a x-on:click="copyToClipBoard" class="uk-icon-button" id="copy-btn" uk-icon="copy"></a>
          </div>

          <div x-show="isLoading">
            <svg class="loader" version="1.1" id="L4" xmlns="http://www.w3.org/2000/svg"
              xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 100 100"
              enable-background="new 0 0 0 0" xml:space="preserve">
              <circle fill="#000" stroke="none" cx="6" cy="50" r="6">
                <animate attributeName="opacity" dur="1s" values="0;1;0" repeatCount="indefinite" begin="0.1" />
              </circle>
              <circle fill="#000" stroke="none" cx="26" cy="50" r="6">
                <animate attributeName="opacity" dur="1s" values="0;1;0" repeatCount="indefinite" begin="0.2" />
              </circle>
              <circle fill="#000" stroke="none" cx="46" cy="50" r="6">
                <animate attributeName="opacity" dur="1s" values="0;1;0" repeatCount="indefinite" begin="0.3" />
              </circle>
            </svg>
          </div>

        </div>
      </div>
      {% else %}
      <div class="d-block text-right mt-3">
        <a href="{% url 'app:login' %}?next=/courses/courses/">
          <button class="btn btn-danger px-3 badge-pill pb-2">share<span class="uk-margin-small-left"
              uk-icon="social"></span></button>
        </a>
      </div>

      {% endif %}
    </div>
    {% endfor %}{% endif %}
  </div>
</div>

<script type="text/javascript">
  function App() {
    return {
      isLoading: false,
      link_generated: false,
      link: {},
      getLink: function (uid) {
        this.isLoading = true;
        // this.createEvent('load',{isLoading:true});
        const url = `/courses/share/${uid}`;
        fetch(url).then(res => res.json()).then(data => {
          // console.log(data);
          this.link = data;
          this.isLoading = false;
          this.link_generated = true;
        }).catch(err => {
        });
      },
      copyToClipBoard: function (event) {
        const { link } = this.link;
        const input = document.createElement('input');
        input.value = link;
        document.body.appendChild(input);
        input.select();
        document.execCommand('copy');
        const copyIcon = document.querySelector('#copy-btn');
        copyIcon.style.background = '#25d366';
        setTimeout(() => copyIcon.style.background = '#f8f8f8', 2000)

      },
      createEvent: function (name, detail) {
        const event = new CustomEvent(name, {
          detail: detail
        });
        document.dispatchEvent(event);
      }
    }
  }



</script>
{% endblock %}

app/templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta proprty="og:title"
    content="School of Resources - Learn anything, anywhere at your convenience! Teach the world with our tools!" />

  {% if page_title %}
  <title>{{page_title}}</title>
  {% else %}
  <title>School of Resources</title>
  {% endif %}

  {% if webmaster %}
  <meta property="og:url" content="{{webmaster.url}}" />
  <meta property="og:type" content="online course" />
  <meta property="og:title" content="{{webmaster.title}}" />
  <meta property="og:description" content="{{webmaster.description|truncatechars:150}}" />
  <meta property="og:image" content="{{webmaster.image_url}}" />
  {% endif %}

  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
  <link rel="stylesheet" href="{% static 'css/uikit.min.css' %}" />
  <link rel="stylesheet" href="{% static 'css/main.css' %}" />
  <link rel="stylesheet" href="{% static 'css/custom.css' %}" />
  <link rel="stylesheet" href="{% static 'css/style.css' %}" />

</head>

<body>
  <div class="container-fluid header">
    <div class="container d-flex flex-wrap align-items-center justify-content-between">
      <div class="d-flex align-items-center justify-content-start header__menu">
        <div class="header__logo py-2">

          <a href="{% url 'app:index' %}">
            <img src="{% static 'assets/logo_1589698236logo (1).png' %}" alt="" />
          </a>
        </div>
        <ul class="nav d-none d-md-flex py-2 align-items-center">
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'app:home' %}">Home</a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'courses:coursesall' %}">Courses</a>
          </li>
          <!-- <li class="nav-item">
            <a class="nav-link" href="{% url 'app:comingsoon' %}">Programmes</a>
          </li> -->
          <li class="nav-item">
            <a class="nav-link" href="{% url 'app:discover' %}">Discover</a>
          </li>
        </ul>
      </div>
      {% if request.user.is_authenticated %}
      <div class="col-lg col-12 d-flex flex-wrap align-items-center justify-content-end py-2 ">
        <li class="nav-item d-flex">
          <div class="wallet">
            <img class="mb-1" src="{% static 'assets/Icon ionic-md-wallet 1.png'%}" alt="">
            <div class="wallet__item ">
              <label class="text-light small mb-1" for="exampleInputPassword1">DISCOUNT</label>
              <input type="password" class="form-control" placeholder="${{request.user.discount_wallet}}" disabled>
            </div>
            <div class="wallet__item">
              <label class="text-light small mb-1">CASH</label>
              <input type="password" class="form-control" placeholder="${{request.user.primary_wallet}}" disabled>
            </div>

          </div>

        </li>

        <!-- <a href="#" target="_blank" rel="noopener noreferrer">Login</a>
                    <label for="" class="m-0 px-3">|</label>
                    <a href="#" target="_blank" rel="noopener noreferrer">Signup</a> -->
        <div class="dropdown">
          <button class="border-0 user-btn" type="button" id="dropdownMenuButton" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            {{request.user.first_name}}
            <span class="uk-margin-small-left" uk-icon="icon: user"></span>
          </button>
          <div class="dropdown-menu dropdown-menu-right mt-3" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item py-2 text-dark" href="#"><span class="uk-margin-small-right"
                uk-icon="icon: user"></span>Profile</a>
            <a class="dropdown-item py-2 text-dark" href="{% url 'app:invite' %}"><span class="uk-margin-small-right"
                uk-icon="icon: user"></span>Invite</a>
            <a class="dropdown-item py-2 text-dark" href="{% url 'app:reset-password' %}"><span
                class="uk-margin-small-right" uk-icon="icon: user"></span>
              Reset Password
            </a>
            <a class="dropdown-item py-2 text-dark" id="logout-button"><span class="uk-margin-small-right"
                uk-icon="icon:  sign-out"></span>Sign out</a>
          </div>
        </div>
        <a href="" class="uk-icon-button ml-3 text-primary position-relative" uk-icon="cart">
          <span class="cart__count" id="cart-count">
            0
          </span>
        </a>
      </div>
      {% else %}
      <div class="col d-flex align-items-center justify-content-end py-2">
        <a href="{% url 'app:login' %}" rel="noopener noreferrer">Login</a>
        <label for="" class="m-0 px-3">|</label>
        <a href="{% url 'app:signup' %}" rel="noopener noreferrer">Signup</a>
      </div>
      {% endif %}

    </div>
  </div>
  <div class="header-offset">
    <!-- just offset -->
  </div>
  <div class="menu-bar d-flex d-md-none align-items-center justify-content-center">
    <div class="container">
      <ul class="nav justify-content-between">
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'courses:coursesall' %}">Courses</a>
        </li>
        <!-- <li class="nav-item">
          <a class="nav-link" href="{% url 'app:comingsoon' %}">Programmes</a>
        </li> -->
        <li class="nav-item">
          <a class="nav-link" href="{% url 'app:discover' %}">Discover</a>
        </li>
      </ul>
    </div>
  </div>

  {% block main %} {% endblock %}

  <!-- footer -->
  <div class="container-fluid footer-top">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center">
        <div class="header__logo py-3 mx-sm-0 mx-auto">
          <img src="{% static 'assets/logo_1589698236logo (1).png' %}" alt="" />
        </div>
        <div class="col-md-6 col-sm py-sm-0 py-3">
          <p class="px-3 m-0 text-light small text-sm-left text-center">
            If you're looking for an affordable, flexible lifelong-learning option, School of Resources could be an
            ideal fit. At
            School of Resources, our mission is to improve lives through learning. Sometimes that means new skills for a
            new career,
            and sometimes it's as simple as realizing a lifelong passion.
          </p>
        </div>
      </div>
    </div>
  </div>

  <div class="container-fluid footer-1 px-0 py-4">
    <div class="container">
      <div class="d-flex flex-wrap">
        <div class="col-md mb-3">
          <label class="text-white w-100 mb-md-4" for="">Useful links</label>
          <ul class="d-flex flex-wrap p-0">
            <a class="text-white w-100 footer__link" href="{% url 'app:aboutus' %}">
              <li class="nav-link pl-0 pb-0 small">About Us</li>
            </a>
            <a class="text-white w-100 footer__link" href="{% url 'app:refer&earn' %}">
              <li class="nav-link pl-0 pb-0 small">Refer & Earn</li>
            </a>
            <a class="text-white w-100 footer__link" href="{% url 'app:contactus' %}">
              <li class="nav-link pl-0 pb-0 small">Contact Us</li>
            </a>
            <!-- <a class="text-white w-100 footer__link" href="{% url 'app:workfromhome' %}">
              <li class="nav-link pl-0 pb-0 small">Work from home</li>
            </a> -->
            <!-- <a class="text-white w-100 footer__link" href="{% url 'courses:coursesall' %}">
              <li class="nav-link pl-0 pb-0 small">
                Digital marketing internship
              </li>
            </a>
            <a class="text-white w-100 footer__link" href="{% url 'app:franchisee' %}">
              <li class="nav-link pl-0 pb-0 small">Franchisee</li>
            </a> -->
          </ul>
        </div>

        <div class="col-md mb-3">
          <a class="nav-link px-0 mr-3 text-white w-100" href="{% url 'app:contactus' %}">
            Contact
          </a>

          <div class="d-flex flex-wrap justify-content-center align-items-start">
            <div class="col px-0">
              <label class="footer-info mt-3 d-flex align-items-start" for="">
                <label for=""><span class="text-info">Address : </span>
                  School of Resources Ltd.
                  <br />
                  46 Franklyn Road,
                  CT2 8PS,
                  Canterbury,
                  Kent, London, United Kingdom.</label>
              </label>
            </div>
          </div>

          <div class="d-flex flex-wrap justify-content-center align-items-start">
            <div class="col px-0">
              <label class="footer-info mt-3 d-flex align-items-start" for="">
                <label for=""><span class="text-info">Powered By : </span>
                  Jags Inventions India Pvt Ltd.
                  <br />
                  46/2892 D, Thykkavu , Vennala, Kochi, Ernakulam, Kerala, India, 682028
                </label>
              </label>
            </div>
          </div>
          <div class="d-flex flex-wrap align-items-start justify-content-center">
            <div class="col px-0">
              <label class="footer-info" for="">
                <label for=""><span class="text-info">Mail : </span><a href="mailto:info@schoolofresources.com"></a>
                  info@schoolofresources.com</label>
              </label>
            </div>
          </div>
          <!-- <div class="d-flex flex-wrap align-items-start justify-content-center">
            <div class="col px-0">
              <label class="footer-info d-flex align-items-start" for="">
              <label for=""><span class="text-info">Phone : </span> <a href="tel:+918921746526"></a>+91 892 174
                6526</label>
            </div>
          </div> -->
          <ul class="nav mt-0">
            <li class="nav-item">
              <a class="nav-link px-0 mr-3 text-white" href="#"><img src="{% static 'assets/fb.png' %}" alt="" /></a>
            </li>
            <li class="nav-item">
              <a class="nav-link px-0 mr-3 text-white" href="#"><img src="{% static 'assets/whatapp.png'%}"
                  alt="" /></a>
            </li>
            <li class="nav-item">
              <a class="nav-link px-0 mr-3 text-white" href="#"><img src="{% static 'assets/twiter.png'%}" alt="" /></a>
            </li>
            <li class="nav-item">
              <a class="nav-link px-0 mr-3 text-white" href="#"><img src="{% static 'assets/insta.png'%}" alt="" /></a>
            </li>
          </ul>
        </div>
        <div class="col-md mb-3 newsletter-container">
          <label class="text-white w-100 mb-md-4" for="">Newsletter</label>
          <p class="small text-light my-0 newsletter pb-2 w-75">
            Stay updated with our latest trends Seed heaven so said place
            winged over given forth fruit.
          </p>
          <div class="form-group position-relative mb-0 subscribe-input">
            <input type="email" class="form-control" placeholder="Enter email address" />
            <button class="btn-primary rounded btn-send">
              <span uk-icon="icon: chevron-right"></span>
            </button>
          </div>
        </div>
      </div>
    </div>
    <div class="container px-1">
      <div class="d-flex w-100 align-items-start justify-content-start flex-wrap">
        <a class="text-light mx-4 py-md-3 pb-2 pointer" href="{% url 'app:termsandconditions' %}">
          <li class="nav-link pl-0 pb-0 small">Terms & Conditions</li>
        </a>
        <a class="text-light mx-4 py-md-3 pb-2 pointer" href="{% url 'app:privacypolicy' %}">
          <li class="nav-link pl-0 pb-0 small">Privacy Policy</li>
        </a>
      </div>
    </div>
    <div class="copyright-1 px-3">
      Powered by <a href="https://jagsinventions.com">Jags Inventions India Pvt Ltd</a>
    </div>
  </div>
  <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.7.3/dist/alpine.min.js" defer></script>
  <script src="{% static 'js/jquery-3.5.1.slim.min.js'%}"></script>
  <script src="{% static 'js/popper.min.js'%}"></script>
  <script src="{% static 'js/bootstrap.min.js'%}"></script>
  <script src="{% static 'js/uikit.min.js'%}"></script>
  <script src="{% static 'js/uikit-icons.mun.js'%}"></script>
  <script src="{% static 'js/script.js'%}"></script>

  <script type="text/javascript">
    document.addEventListener("DOMContentLoaded", function () {
      lg = document
        .getElementById("logout-button")
        .addEventListener("click", function () {
          const xhr = new XMLHttpRequest();
          xhr.open("GET", "/logout/", true);
          xhr.send();
          xhr.onreadystatechange = function () {
            if (
              this.readyState === XMLHttpRequest.DONE &&
              this.status === 200
            )
              window.location.reload();
          };
        });
    });
  </script>
</body>

</html>

app/templates/new-index.html
{% extends 'main.html' %}
{% load static %}



{% block main %}
<link rel="stylesheet" type="text/css" href="{% static 'css/new-style.css' %}">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css"
    integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600;700;800&display=swap" rel="stylesheet">

<div class="hero-sec">
    <div class="container">
        <div class="row">
            <div class="col-md-7 order-2">
                <div class="hero-content">
                    <div class="hero-title">The Finest <span>E-Learning Platform</span>, Where Great Minds Grow.</div>
                    <div class="hero-sub-title">Explore London Based Top Certificate Courses and Programs</div>
                    <a href="{% url 'courses:coursesall' %}" class="btn btn-style">Start Learning <i
                            class="fas fa-chevron-right"></i></a>
                </div>
            </div>
            <div class="col-md-5 hero-img-sec order-sm-1"><img src="{% static 'assets/hero-img.svg' %}"
                    class="img-fluid"></div>
        </div>
    </div>
</div>


<section class="feature-sec">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 features-img-sec order-2"><img src="{% static 'assets/features-img.svg' %}"
                    class="img-fluid"></div>
            <div class="col-lg-6 order-1">
                <div class="features-title">Our Key Features <i class="fas fa-chevron-right"></i></div>
            </div>
            <div class="col-lg-6 order-3">
                <div class="features-list">
                    <img src="{% static 'assets/Accessibility.svg' %}" class="img-fluid">
                    <div class="feature-content">
                        <div class="feature-title">Accessibility</div>
                        <p>SOR learning platform is easy to use and have worldwide accessibility. You can interact with
                            experts
                            through chats and call support.</p>
                    </div>
                </div>
                <!--features-list-->

                <div class="features-list">
                    <img src="{% static 'assets/evaluation.svg' %}" class="img-fluid">
                    <div class="feature-content">
                        <div class="feature-title">Evaluation</div>
                        <p>Evaluate yourselves with mock tests and doubt ticketing option. Get high-quality video
                            contents and
                            study materials. </p>
                    </div>
                </div>
                <!--features-list-->

                <div class="features-list">
                    <img src="{% static 'assets/Usage.svg' %}" class="img-fluid">
                    <div class="feature-content">
                        <div class="feature-title">Usage</div>
                        <p>Avail international learning experience and free access to study materials, along with
                            unlimited access
                            to videos.</p>
                    </div>
                </div>
                <!--features-list-->

                <div class="features-list">
                    <img src="{% static 'assets/Uniqueness.svg' %}" class="img-fluid">
                    <div class="feature-content">
                        <div class="feature-title">Uniqueness</div>
                        <p>Yes, SOR is 100% secure! You can save your travel expense and time on your schooling and plan
                            your
                            classes at your fingertip. </p>
                    </div>
                </div>
                <!--features-list-->

                <div class="features-list">
                    <img src="{% static 'assets/Scholarships.svg' %}" class="img-fluid">
                    <div class="feature-content">
                        <div class="feature-title">Scholarships</div>
                        <p>A wide variety of scholarships are awaiting the students that can add to their learning
                            experience and
                            opportunities.</p>
                    </div>
                </div>
                <!--features-list-->

            </div>
        </div>
    </div>
</section>



<section>
    <div class="container">
        <div class="sec-title">
            OUR <span>COURSES</span>
        </div>
        <div class="row">
            {% for course in courses %}
            <div class="col-lg-4 col-md-6">
                <div class="course-list">
                    <a href="{% url 'courses:detail' course.uid %}"><img src="{{course.course_image.url}}"
                            class="img-fluid course-list-img"></a>
                    <a href="{% url 'courses:detail' course.uid %}">
                        <div class="course-title">{{course.name}}</div>
                    </a>
                    <p class="line-clamp">{{course.description}}</p>
                    <div class="btn-sec">
                        <a href="{% url 'courses:detail' course.uid %}">View More <i
                                class="fas fa-angle-double-right"></i></a>


                    </div>
                </div>
            </div>
            {% endfor %}

        </div>
</section>

{% endblock main %}

app/templates/refer-and-earn.html
{% extends 'main.html' %}
{% load static %}
{% block main %}


<!-- page content section -->
<div class="container page-container">
    <div class="row">
        <div class="col-md-12">
            <div class="page-title">Refer & Earn</div>
            <h3>Refer Someone You Know and Get amazon Vouchers Worth ₹500!</h3>
            <p>By 2025 India’s tech sector will sustain up to 65 million jobs! Know anyone who can meet this increasing
                demand? Then, share this gift of education with them now!</p>

            </a>
            <a href="{% url 'app:invite' %}" class="btn btn-main mr-2">Sign Up & Refer</a>
            ​
            <div class="step-by-step">
                <h3>How Do I Refer?</h3>
                <h4>It only takes 3 simple steps to change someone’s life!</h4>
                ​
                <div class="step-sec">
                    <h4>1. Sign Up & Share</h4>
                    <p>Sign up on our website and get your referral code to share. Share your referral code with someone
                        you know who wishes to join one of our programs.</p>
                </div>
                ​
                <div class="step-sec">
                    <h4>2. Apply Code</h4>
                    <p>Your friend can apply for their desired course with your referral code to be eligible for the
                        discount.</p>
                </div>
                ​
                <div class="step-sec">
                    <h4>3. Get Referral Benefits</h4>
                    <p>Yay! You will receive your referral rewards once the referee makes the payment for their desired
                        course.</p>
                </div>
                ​
                <div class="step-sec">
                    <a href="{% url 'courses:coursesall' %}" class="btn btn-main mr-2">Find the perfect course for your
                        friend here!</a>
                </div>
            </div>
            ​
            ​
        </div>
    </div>
</div>
<!-- End page content section -->
​
​
​

{% endblock %}